export { setAnalyticsClient } from './client'
export {
  hashAdventureId,
  trackBookingClick,
  trackGpxUploaded,
  trackMapOpened,
  trackPoiDetailOpened,
  trackPoiSearchTriggered,
  trackLiveModeActivated,
  trackLandingCtaClicked,
  trackSignupStarted,
  trackSignupCompleted,
  trackLoginCompleted,
} from './events'
export type {
  AnalyticsClient,
  AnalyticsEvent,
  AuthMethod,
  BookingClickProps,
  GpxUploadedProps,
  LandingCtaClickedProps,
  LandingCtaPlacement,
  LiveModeActivatedProps,
  LoginCompletedProps,
  MapOpenedProps,
  PoiDetailOpenedProps,
  PoiSearchTriggeredProps,
  SignupCompletedProps,
  SignupStartedProps,
  UserTier,
} from './types'
